### ISSUE TITLE
Sugestão MVP Site - Alterações

### ISSUE THREAD

**Issue by Vanessapcs** [SouJunior/products#11]
**Seção I - Hero**

- Mudar a frase para: **Experiência real de trabalho em projetos, construída por uma empresa de tecnologia!**

**Seção II - O que é o Sou Junior?**

![Image](https://user-images.githubusercontent.com/91374502/207427590-2145492f-d414-44b8-9608-9360f147dfd2.png)

- Alterar o nome da seção para "Sobre a Iniciativa".
- Retirar a "galaxia" (ela não tem muita utilidade) e expandir o texto em toda a largura da página.
- Ajustar o texto "Sobre a Iniciativa" para:

A SouJunior é um projeto Open Source com o propósito de preparar os profissionais juniores para o mercado através da construção de alguns produtos e do conhecimento prático do dia a dia de trabalho de uma empresa de tecnologia. Para que essa iniciativa se torne real, contamos com um time de voluntários, desde iniciantes no mercado de tecnologia até profissionais experientes que atuam como mentores e lideram os times.

A SouJunior contará com um portfolio de produtos que proporcionará visibilidade aos juniores, os conectando tanto aos profissionais de recrutamento, para que a tão almejada primeira experiência seja alcançada, quanto aos mentores que irão orientá-los em sua jornada profissional que está apenas começando.

Portanto, participar da Sou Junior é uma grande chance de adquirir experiência e de participar de um projeto de alta visibilidade, com o amparo de uma rede de apoio, além do networking e conexão com novas oportunidades.

**Seção III - Áreas de Atuação**

![Image](https://user-images.githubusercontent.com/91374502/207428050-1bb3d66b-f9a1-4b73-8dfd-2970ebea8dc0.png)

- Alterar o nome "APM" para "Produtos". APM é um cargo e pode gerar dúvida sobre o que significa. Já "Produtos" é a área.

**Seção IV - Quem pode participar?**

![Image](https://user-images.githubusercontent.com/91374502/207428471-d8101f3a-dd69-4c30-8f34-8000d77daeba.png)

- Substituir o texto "Quem pode participar" para:
Aqui na SouJunior, você poderá participar do projeto de muitas maneiras. 
Temos oportunidades para profissionais nível júnior e mentores das mais diversas áreas, caso você tenha o interesse de colocar a "mão na massa" e construir esse projeto conosco.
Porém, se o interesse for de patrocinar a iniciativa para que ela continue por muito tempo, você poderá se tornar nosso apoiador ou parceiro.
Confira ao lado todas as categorias de participação disponíveis na SouJunior, preencha os formulários das quais for do seu interesse e entraremos em contato!

**Comment by crismpimentel** [comment]
@anikape @thaygjo meninas, favor colocar aqui no card a data que vocês podem entregar estes ajustes.
@SouJunior/frontend favor colocar aqui a data para os ajustes de desenvolvimento.

**Comment by anikape** [comment]
Seção I - Ok
Seção II - Galáxia retirada, frase alterada. Estamos alterando o alinhamento. Seria interessante essa alteração no wireframe 
https://www.figma.com/file/9FZH7FhqQt3cqFNASY2q8F/Wireframe-Site?node-id=474%3A1245&t=TJL0unBNWfjjCtXS-0

Seção III - Ok

Seção IV - Ok

Reforço que estamos trabalhando em alguns pontos críticos, como o carrossel. Por hora, mantendo o prazo previamente acordado, 22/12.

**Comment by Leacyntra10** [comment]
@anikape oi Ana, inclui os textos revisados (Seções II e IV), favor substituir.

**Comment by Leacyntra10** [comment]
@anikape oa textos revisados  <html>
<body>
<div class="adn ads" data-message-id="#msg-a:r3139959366467306299" data-legacy-message-id="18521c19ede9b2bf" style="border-left: none; padding: 0px; display: flex; color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="gs" style="margin: 0px; padding: 0px 0px 20px; width: 826.392px;"><div class=""><div id=":1yv" class="ii gt" jslog="20277; u014N:xr6bB; 4:W251bGwsbnVsbCxbXV0." style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem;"><div id=":1yu" class="a3s aiL " style="font: small / 1.5 Arial, Helvetica, sans-serif; overflow: hidden;"><div dir="auto"><div dir="auto">A SouJunior é um projeto Open Source com o propósito de preparar os profissionais juniores para o mercado através da construção de alguns produtos e do conhecimento prático do dia a dia de trabalho de uma empresa de tecnologia. Para que essa iniciativa se torne real, contamos com um time de voluntários, desde iniciantes no mercado de tecnologia até profissionais experientes que atuam como mentores e lideram os times.</div><div dir="auto"><br></div><div dir="auto">A SouJunior contará com um portfolio de produtos que proporcionará visibilidade aos juniores, os conectando tanto aos profissionais de recrutamento, para que a tão almejada primeira experiência seja alcançada, quanto aos mentores que irão orientá-los em sua jornada profissional que está apenas começando.</div><div dir="auto"><br></div><div dir="auto">Portanto, participar da Sou Junior é uma grande chance de adquirir experiência e de participar de um projeto de alta visibilidade, com o amparo de uma rede de apoio, além do networking e conexão com novas oportunidades.</div></div><div class="yj6qo"></div><div class="adL"></div></div></div><div class="hi" style="border-bottom-left-radius: 1px; border-bottom-right-radius: 1px; padding: 0px; width: auto; background: rgb(242, 242, 242); margin: 0px;"></div></div></div><div class="ajx" style="clear: both;"></div></div><div class="gA gt acV" style="font-size: 0.875rem; padding: 0px; width: auto; border-bottom-left-radius: 0px; border-bottom-right-radius: 0px; border-top: none; margin: 0px; background: rgb(255, 255, 255); color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="gB xu" style="border-top: 0px; padding: 0px;"><div class="ip iq" style="clear: both; margin: 0px; padding: 16px 0px; border-top: none;"><div id=":1yw">

  | ResponderEncaminhar
-- | --


</div></div></div></div>
</body>
</html>

**Comment by anikape** [comment]
@Leacyntra10 qual o da seção II e o da IV?

**Comment by Leacyntra10** [comment]
@anikape 

<html>
<body>
<div class="adn ads" data-message-id="#msg-a:r3139959366467306299" data-legacy-message-id="18521c19ede9b2bf" style="border-left: none; padding: 0px; display: flex; color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="gs" style="margin: 0px; padding: 0px 0px 20px; width: 826.392px;"><div class=""><div id=":1yv" class="ii gt" jslog="20277; u014N:xr6bB; 4:W251bGwsbnVsbCxbXV0." style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem;"><div id=":1yu" class="a3s aiL " style="font: small / 1.5 Arial, Helvetica, sans-serif; overflow: hidden;"><div dir="auto"><div dir="auto">A SouJunior é um projeto Open Source com o propósito de preparar os profissionais juniores para o mercado através da construção de alguns produtos e do conhecimento prático do dia a dia de trabalho de uma empresa de tecnologia. Para que essa iniciativa se torne real, contamos com um time de voluntários, desde iniciantes no mercado de tecnologia até profissionais experientes que atuam como mentores e lideram os times.</div><div dir="auto"><br></div><div dir="auto">A SouJunior contará com um portfolio de produtos que proporcionará visibilidade aos juniores, os conectando tanto aos profissionais de recrutamento, para que a tão almejada primeira experiência seja alcançada, quanto aos mentores que irão orientá-los em sua jornada profissional que está apenas começando.</div><div dir="auto"><br></div><div dir="auto">Portanto, participar da Sou Junior é uma grande chance de adquirir experiência e de participar de um projeto de alta visibilidade, com o amparo de uma rede de apoio, além do networking e conexão com novas oportunidades.</div></div><div class="yj6qo"></div><div class="adL"></div></div></div><div class="hi" style="border-bottom-left-radius: 1px; border-bottom-right-radius: 1px; padding: 0px; width: auto; background: rgb(242, 242, 242); margin: 0px;"></div></div></div><div class="ajx" style="clear: both;"></div></div><div class="gA gt acV" style="font-size: 0.875rem; padding: 0px; width: auto; border-bottom-left-radius: 0px; border-bottom-right-radius: 0px; border-top: none; margin: 0px; background: rgb(255, 255, 255); color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="gB xu" style="border-top: 0px; padding: 0px;"><div class="ip iq" style="clear: both; margin: 0px; padding: 16px 0px; border-top: none;"><div id=":1yw">

  | ResponderEncaminhar
-- | --


</div></div></div></div>
</body>
</html>

**Comment by Leacyntra10** [comment]
@anikape oi Ana, só um momento por favor, meu Girhub travou.

**Comment by Vanessapcs** [comment]
@anikape olha na própria US. Ela está atualizada com os textos. Em cada seção foi colocado os textos para mudar.
Qualquer dúvida pode escrever aqui que respondo. A @Leacyntra10 está com um problema na maquina.

**Comment by edcabralc** [comment]
Boa noite, desculpem só vi a notificação agora a noite. a @anikape já adiantou bastante as alterações, vou verificar o que está pendente para concluir.

**Comment by edcabralc** [comment]
> @anikape olha na própria US. Ela está atualizada com os textos. Em cada seção foi colocado os textos para mudar. Qualquer dúvida pode escrever aqui que respondo. A @Leacyntra10 está com um problema na maquina.

Desculpa @Vanessapcs , mas não localizei o backlog do site, pode marcar aqui para vermos as US?

**Comment by Vanessapcs** [comment]
@edcabralc é essa US mesmo que estamos falando. Lá no início deste próprio card.

**Comment by edcabralc** [comment]
Bom dia a todos, atualizações realizadas.

**Comment by Vanessapcs** [comment]
@edcabralc obrigada! Conseguiria disponibilizar o link para que a @Leacyntra10 e a @crismpimentel possam validar?

**Comment by anikape** [comment]
Bom dia. @Vanessapcs o deploy está apresentando erro. Tenho uma mentoria às 10h com o mentor front-end. Vou verificar com ele o porquê disso e assim que finalizar te dou uma posição.

**Comment by edcabralc** [comment]
Bom dia! Segue o link para verificar as atualizações

https://deploy-preview-76--soujunior.netlify.app/

**Comment by Vanessapcs** [comment]
@anikape obrigada pelo retorno. Só não esqueça de não disponibilizar o produto no ar sem combinar com a @Leacyntra10 ou @crismpimentel sobre isso, porque elas que  orquestarão o delivery, ok? Então as mantenha informadas, para que elas possam conversar com mídia e Brandão, deixar tudo organizado, montar os comunicados e dar o ok para que você possa colocar no ar.
Abraços!

**Comment by Vanessapcs** [comment]
Obrigada @edcabralc !
@Leacyntra10 e @crismpimentel podem começar as validações. Caso alguma coisa não esteja de acordo, sinalize o @edcabralc para que ele possa ajustar.

**Comment by Vanessapcs** [comment]
@anikape e @edcabralc é possível deixar o "Menu" do site fixado na tela conforme a gente vai rolando a página?

Vou deixar um exemplo aqui: http://www.alln1hob.com/#home

O bacana desse exemplo, é que além de deixarem o menu fixado, o item que está sendo visto no momento em tela vai ficando em destaque no menu.

**Comment by anikape** [comment]
@Vanessapcs foi acordado em reunião que novas funcionalidades serão implementadas na V2. 

Porém, vamos tentar.

**Comment by crismpimentel** [comment]
Oi, @edcabralc, boa tarde!
Estou fazendo o pente fino no link de deploy que você enviou! Obrigada pelo tanto que você e a @anikape se empenharam para desenvolver as alterações! :)
Vou postar aqui algumas pequenas alterações para que eu e a @Leacyntra10 possamos validar, ok?

**Comment by crismpimentel** [comment]
Seção Hero: retirar a vírgula antes de contruída.

![Image](https://user-images.githubusercontent.com/119442664/208466070-0a86feb0-d7ec-4edb-a43c-d608a3aff6ae.png)

**Comment by crismpimentel** [comment]
Seção II - Sobre a Iniciativa (colocar hífen na expressão dia-a-dia)



![Image](https://user-images.githubusercontent.com/119442664/208466376-2f65ea39-0a70-42d7-92e5-bd2cbc6aee03.png)

**Comment by crismpimentel** [comment]
Seção III - Áreas de atuação (trocar o NO SouJunior para NA SouJunior)



![Image](https://user-images.githubusercontent.com/119442664/208466958-9fdb76a9-0638-435f-afc2-4645f7514831.png)

**Comment by crismpimentel** [comment]
Seção IV - Quem pode participar, aba Sou Junior (colocar o acento na palavra têm, pois refere-se a plural)



![Image](https://user-images.githubusercontent.com/119442664/208467355-b710e70f-dbf1-4320-b32e-07347ba92d97.png)

**Comment by crismpimentel** [comment]
Seção IV - Quem pode participar, aba Sou Junior (dar espaçamento entre Linkedin e pode)
Seção IV - Quem pode participar, aba Sou Junior (trocar participar DO SouJunior por DA SouJunior)


![Image](https://user-images.githubusercontent.com/119442664/208467611-0df43494-2479-4efd-a3df-6be8a31ba20e.png)

**Comment by crismpimentel** [comment]
Seção IV - Quem pode participar, aba Sou Mentor (trocar contribuir para o SouJunior para contribuir para a SouJunior)



![Image](https://user-images.githubusercontent.com/119442664/208468071-3d439c11-7fb2-4059-92ed-9214dd9cecb7.png)

**Comment by crismpimentel** [comment]
Seção IV - Quem pode participar, aba Sou Apoiador (corrigir o texto para:




![Image](https://user-images.githubusercontent.com/119442664/208468361-9a376432-2e82-45a7-9fa0-cba01e8845d7.png)

**Comment by crismpimentel** [comment]
Seção IV - Quem pode participar, aba Sou Apoiador (corrigir o texto para:

**Pessoas especialistas que se disponham A palestrar** 



![Image](https://user-images.githubusercontent.com/119442664/208468700-40c71eb2-0018-4e37-b916-18c71f4f3ad9.png)

**Comment by crismpimentel** [comment]
Seção IV - Quem pode participar, aba Sou Apoirador (corrigir o texto para:

**Recrutadores e empresas dispostas a contratar ou que priorizem a contratação DOS profissionais Juniors voluntários DA SouJunior.**


![Image](https://user-images.githubusercontent.com/119442664/208469057-0ac3c2fa-6212-4896-999d-bf2c96bcaf39.png)

**Comment by crismpimentel** [comment]
Seção IV - Quem pode participar, aba Sou Apoiador (retirar o espaçamento entre os textos e corrigir para:

**Se você pode contribuir para A SouJunior como** 


![Image](https://user-images.githubusercontent.com/119442664/208469413-0c99a9a3-91eb-4f37-ae5c-09a5b9e66b6e.png)

**Comment by crismpimentel** [comment]
Seção IV - Quem pode participar, aba Comunidade (corrigir os textos, alterando os artigos de O para A)
Incluir vírgula após SouJunior: **Acesse o servidor SouJunior no Discord e do Github do SouJunior, espie e**



![Image](https://user-images.githubusercontent.com/119442664/208469648-31e35b01-6054-445a-ad7c-450d643a3884.png)

**Comment by anikape** [comment]
@Vanessapcs seguindo a linha de pensamento do @edcabralc, nós usamos os textos do Wireframe. Para otimizar o código, copiamos e colamos o que está ali. Entendemos que tudo que consta lá já foi revisado e aprovado antes de seguir para o desenvolvimento. Não sei como foi feito, mas seria bom que nas próximas versões todos os textos fossem de fato previamente revisados.

**Comment by Vanessapcs** [comment]
Oi @anikape pode deixar! Como aqui estamos fazendo em um modelo "war room" para o lançamento, estamos tentando deixar o mais organizado possível e pode acontecer isso. Eu não revisei os textos dentro das guias, porque não tinha acesso e pedi para as meninas fazerem hoje. Os demais, eu escrevi ontem mesmo, então acabou acontecendo de esquecer um acento. 
Porém, todas as demais User Stories que vocês receberem pós go live, já estarão totalmente revisadas.

**Comment by Dande94** [comment]
onde eu dei '👍🏽' foi atulizado conforme solicitado...

**Comment by Dande94** [comment]
já subi as alterações pro Github. como não tenho acesso a validação do PR, estou aguardando alguém validar para a atulização ser efetivada ao projeto...

**Comment by edcabralc** [comment]
> já subi as alterações pro Github. como não tenho acesso a validação do PR, estou aguardando alguém validar para a atulização ser efetivada ao projeto...

PR, aprovado!

**Comment by crismpimentel** [comment]
@edcabralc @anikape Bom dia!
Vocês podem passar para mim e a @Leacyntra10 o link com as alterações realizadas para que possamos fazer a nossa validação?

**Comment by edcabralc** [comment]
Bom dia, @crismpimentel !

Link para validação:
https://deploy-preview-80--soujunior.netlify.app/

**Comment by crismpimentel** [comment]
Pessoal, está ótimo! Só falta uma alteração:

Seção Áreas de Atuação: Alterar **Aqui no SouJunior** para Aqui **na** SouJunior

Quando fizerem a alteração, nos avise aqui, validaremos e encaminharemos para a mídia!

Muito obrigada! :)

![Image](https://user-images.githubusercontent.com/119442664/208697321-5ae2b289-76a3-4b59-a1dd-60cd94185536.png)

**Comment by Leacyntra10** [comment]
@edcabralc Bom dia Edvaldo.
Ficou ótimo, aguardamos as alterações para validarmos. Obrigada

**Comment by crismpimentel** [comment]
@edcabralc @anikape @Dande94 @Vanessapcs @Leacyntra10 Versão 1 do site validada!!!!
Parabéns a todos!
=)

**Comment by anikape** [comment]
Parabéns equipe. 🎉

**Comment by edcabralc** [comment]
Bom dia, pessoal! Validada as alterações, podemos encerrar essa Issue?

**Comment by Leacyntra10** [comment]
@edcabralc  Seção IV - Quem pode participar, aba Comunidade no desktop aparece: a mão na massa e ( como está, separado) mas no celular aparece a mao na massae (sem espaço entre massa e).
Peço a você, colocar "mão na massa" entre aspas.

**Comment by anikape** [comment]
@Leacyntra10 foi corrigido? Me avisa q mando a correção.

**Comment by Leacyntra10** [comment]
Bom dia @anikape, o @edcabralc ficou de verificar e corrigir ontem, mas ainda não me respondeu.
Oi @edcabralc foi corrigido?

**Comment by anikape** [comment]
@Leacyntra10 alterações feitas.; Já mandamos para o repositório.

**Comment by Leacyntra10** [comment]
Obrigada @anikape.
