### ISSUE TITLE
Ajustar o Hero - Inclusão de pessoas negras

### ISSUE THREAD

**Issue by crismpimentel** [SouJunior/products#22]
**Definição:**

Como usuário, eu gostaria de acessar o site da SouJunior e visualizar a Hero com a inclusão de duas pessoas de pele negra (um homem e uma mulher) ressaltando a inclusão e diversidade  da comunidade SouJunior.

**Descrição:**

A SouJunior abrange todo o universo de diversidade em sua comunidade, portanto, é necessário alterar, na figura do Hero, a cor da pele para negra em 1 mulher e 1 homem que estão presentes na figura atual.

**Protótipo:**

Realizei um "de>para" nas imagens, demonstrando como deverá ficar a nova Hero , com a inclusão de pessoas negras.

**_### IMAGEM ATUAL ###_**:

![Image](https://user-images.githubusercontent.com/96747949/221382156-28c3c9f6-acd5-4079-b318-9daf8b2ab528.png)

**_### NOVA HERO ###_**:

> Opção 01:

![Image](https://user-images.githubusercontent.com/96747949/221382341-de538c02-f0d3-449b-8c74-497c65d11f7b.png)

> Opção 02:

![Image](https://user-images.githubusercontent.com/96747949/221382715-fe645b80-ea96-4641-a4cf-3e5a43226118.png)

**Critérios de Aceite Seção Hero:**

Quando o usuário acessar o site SouJunior, imediatamente visualizará a figura do Hero com a alteração na cor da pele para negra de 1 mulher e 1 homem.

**Comment by Vanessapcs** [comment]
@Leacyntra10 @midigalvao 

Como a Cris não está mais consoco, marquei as duas na US para que vocês decidam qual apresentará esse item na Sprint Planning.
Quem for definido, leia a US com calma e qualquer dúvida, me chamem.

**Comment by andyarauj0** [comment]
@Vanessapcs eu acho que o hero atualizado focou apenas da inclusão de pessoas negras.
Gosto do primeiro, por incluir pessoas com deficiência, e acho que a inserção de pessoas negras poderia acontecer lá. O que acha?

**Comment by Vanessapcs** [comment]
@andyarauj0 na realidade o Hero se manterá. A ideia é pegarmos 2 pessoas do Hero e alterar a cor da pele. 

Porém, se a mensagem não foi passada corretamente, então vale a pena um ajuste na descrição, explicando um pouco melhor.

@midigalvao poderia olhar essa US e detalha-la um pouco mais?

**Comment by andyarauj0** [comment]
@Vanessapcs acho que o que me gerou confusão foi o" #DE" "#PARA" dos protótipos. A segunda imagem é bem diferente e aí acaba dando a entender numa alteração completa do Hero.
@midigalvao vamos só alinhar melhor a descrição com os protótipos

**Comment by Vanessapcs** [comment]
@andyarauj0 mas esse feedback é super importante!!! Mostra que realmente precisamos organizar e de repente "cortar" o Hero da versão corrigida, deixando so a moça, para que as pessoas possam entender como será a mudança.

**Comment by priscilassouza** [comment]
Olá, pessoal! Ajustes realizados!

**Comment by anikape** [comment]
Alterações realizadas conforme solicitado..

**Comment by anikape** [comment]
@RntSaturnino @Samueldiasp para aprovação

**Comment by andyarauj0** [comment]
@anikape pode seguir com a alteração no site com a nova hero

**Comment by Vanessapcs** [comment]
@RntSaturnino @Samueldiasp vocês precisam olhar o figma e darem o ok para que a @anikape possa aplicar.

**Comment by Samueldiasp** [comment]
@priscilassouza @anikape 

Bom dia, pessoal! Para mim está de acordo! Obrigado!

**Comment by anikape** [comment]
Bom dia. A modificação foi feita o PR já está no github para aprovação.

**Comment by sabrinamir** [comment]
@limaricardo @wandersonDeve esta US está parada. Poderiam validar?

**Comment by sabrinamir** [comment]
@brcaua e @wandersonDeve  poderiam validar a parte de frontend e backend para finalizarmos esta US?

**Comment by brcaua** [comment]
Validado.
