### ISSUE TITLE
Páginas de cadastro para mentores

### ISSUE THREAD

**Issue by Vanessapcs** [SouJunior/products#257]
**Definição:**

**Como** usuário,
**Gostaria** de demonstrar interesse em ser mentor da Sou Junior,
**Tendo** acesso a mais informações sobre como mentorar nos projetos.

---

**Descrição:**

Para que o usuário interessado em mentorar formalize o seu interesse será necessário realizar uma inscrição pelo site, na aba "Sou Mentor".

---

**Protótipo:**

Versão Web

![Image](https://github.com/SouJunior/products/assets/98753928/8c0be9a8-2e6d-433f-9c57-5b3b0fd53634)

![Image](https://github.com/SouJunior/products/assets/98753928/87a369a4-a00d-41c0-bca7-0359e643bc12)

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?page-id=3167%3A15581&type=design&node-id=3167-15631&viewport=520%2C408%2C0.39&t=GxvA4PTVEPwXo5xJ-8&scaling=min-zoom&starting-point-node-id=3167%3A15631&hide-ui=1

---

**Critérios de aceite**

1- O Mentor entrará no site da SouJunior;

2- O usuário poderá clicar em "Faça parte" e ser direcionado para a seção "Faça você também parte da nossa comunidade!";

3- Ao clicar na seção "Sou Mentor", o usuário terá acesso à descrição da seção;

4- Ao clicar no botão "Quero Participar" o usuário será redirecionado para outra página, para fazer sua inscrição;

5- Na página de inscrição o usuário deverá preencher os dados obrigatórios manualmente;

6 - O usuário deverá informar seu nome completo;
O campo "Nome completo" deverá ter capacidade para 100 caracteres.
*Campo obrigatório

7- O campo "Em que área gostaria de atuar?" deverá ser preenchido através do drop-down (lista);
*Campo obrigatório

8- O drop-down (lista) deverá conter as opções: Produtos, Business, Tech Recruiting, Scrum Master, Dados, Mobile, Front End, Devops, UX, Back End e Q&A;
*Campo obrigatório

9- O campo "E-mail" deve ser preenchido manualmente e obrigatoriamente;
*Campo obrigatório

10- Para ser considerado um e-mail válido o mesmo dever conter o símbolo de @ + o domínio do e-mail + .com/.net/.br;

11 -Caso o e-mail não siga os critérios de validação, então o sistema deverá apresentar uma mensagem abaixo do campo com a descrição: E-mail inválido.;

12- O campo "Confirmação de e-mail" deve ser preenchido manualmente e obrigatoriamente;
*Campo obrigatório

13- Caso os campos de e-mail e confirmação estejam divergentes, deverá ser apresentada a mensagem "e-mail divergente abaixo do campo;

14- O campo "LinkedIn" deve ser preenchido manualmente e obrigatoriamente;
*Campo obrigatório

15- O campo "Nos conte um pouco sobre você e porque gostaria de fazer parte da SouJunior?" deverá ter capacidade para 500 caracteres (com contador de caracteres);
*Campo obrigatório

16- Caso os campos obrigatórios não forem preenchidos, ao clicar em "Enviar" aparecerá uma mensagem em vermelho no campo não preenchido "O campo não foi preenchido";

17- Após o último campo, existirá um botão: "Enviar";

18- O usuário deverá ter acesso ao botão "**Enviar **" para enviar os dados preenchidos;

19- Quando o usuário clicar em "Enviar", aparecerá uma pop-up com a mensagem "Dados enviados com sucesso";

20- Os dados do usuário deverão ser direcionados para o e-mail do "Brandão"; [[wouerner@soujunior.tech](mailto:wouerner@soujunior.tech)];

21- O usuário será redirecionado para a "home" após clicar em "Enviar";

22- Se o usuário clicar em voltar no canto superior a esquerda caso desista de preencher os dados;

23- Após clicar em "Voltar" aparecerá um pop-up com um botão escrito "Você deseja mesmo cancelar a inscrição?" com a opção "Sim" e "Não";

24- Caso o cliente opte por "sim" ele será redirecionado para a "home";

25- Caso o cliente opte por "não" os dados continuarão preenchidos e ele deverá clicar em "Enviar" para enviar a inscrição;

26- Após o envio, os dados deverão ser apagados.

27- Com os dados enviados deverá ser enviado um e-mail automático de confirmação com os detalhes da inscrição e instruções sobre o próximo passo.

Assunto: Confirmação de Inscrição | SouJunior

Olá, {{CANDIDATE_FIRST_NAME}}.
Agradecemos seu interesse pela área {{JOB_NAME}}, seu perfil passará por uma triagem. Caso você seja aprovado, aguarde as próximas etapas através do e-mail cadastrado.
Nos preocupamos em te dar um retorno o mais rápido possível. Para isso, estamos realizando a análise dos perfis com bastante atenção, e isso pode levar alguns dias.

Nome completo:
Área de atuação:
LinkedIn:
Nos conte um pouco sobre você e por que gostaria de atuar na SouJunior:

Até breve com mais notícias,
{{SÍMBOLO DA SOUJUNIOR}}
"

**Protótipo do e-mail:**

Apresentação:
https://www.figma.com/proto/jSRZ3oteNw72k5a53sEwRq/SITE---Sou-Junior--Ago-2023?page-id=3167%3A15581&type=design&node-id=3528-40&viewport=-1238%2C475%2C0.65&t=7p52e1Ljo6AIgrG8-1&scaling=min-zoom&starting-point-node-id=3528%3A40&show-proto-sidebar=1&mode=design

Arquivo:
https://www.figma.com/file/jSRZ3oteNw72k5a53sEwRq/SITE---Sou-Junior--Ago-2023?type=design&node-id=3167%3A15581&mode=design&t=te5MVZWiDFrEr3rg-1

---

**Informações Adicionais:** --

---

**DoR - Definition of Ready**

- [x]  O design/wireframe foi definido e aprovado.
- [x] A tarefa foi priorizada de acordo com o backlog e com as necessidades.
- [ ] Os critérios de aceite estão claramente definidos a serem executada pela equipe.
- [ ] As dependências do projeto foram identificadas e resolvidas e documentadas.
- [x] A equipe entendeu e concordou com as definições de "pronto" para a tarefa.

---

**DoD - Definition of Done**

- [ ]  Todos os requisitos funcionais definidos foram implementados e testados.
- [ ]  O site está em conformidade com as especificações.
- [ ] O site é responsivo e funciona em diferentes tamanhos de tela e dispositivos.
- [ ] O site é acessível para usuários com deficiência.
- [ ] O tempo de carregamento da página é aceitável.
- [ ] O código foi testado por meio de testes automatizados.
- [ ] Os testes de aceitação do usuário foram realizados com sucesso.
- [ ] O design do site está de acordo com as diretrizes definidas.
- [ ] A documentação do código é completa e atualizada.
- [ ]  A documentação do usuário está disponível e é fácil de usar.
- [ ] O site foi implantado com sucesso no ambiente de produção.
- [ ] As configurações do servidor foram realizadas conforme as especificações definidas pelo cliente.

**Comment by lairareis** [comment]
@Vanessapcs finalizado.

**Comment by RamisOliveira** [comment]
Bom dia @lairareis e @Vanessapcs tudo bem? 

**8 -** No drop-down, observamos que há nomes de áreas, como "Agilidade", que não correspondem a profissões específicas. A fim de melhorar a seleção, sugiro a retirada dessa opção e a inclusão de opções adicionais representando profissões comuns relacionadas à área de Agilidade, como "Scrum Master" e "Agile Coach" e outras opções relevantes. Isso proporcionará maior precisão e facilidade para os usuários ao escolherem a opção que melhor corresponde à sua ocupação dentro da área de Agilidade.

**15-** O campo "Nos conte um pouco sobre você e porque gostaria de fazer parte da SouJunior?" Deve ser obrigatório, pois essa informação nos ajudará a avaliar o alinhamento dos candidatos com nossa cultura, valores e propósito, além de identificar suas habilidades e interesse em contribuir para o desenvolvimento e crescimento da SouJunior. 

**19-** Após o usuário preencher o formulário e clicar em "Enviar", uma pop-up amigável será exibida com a mensagem "Dados enviados com sucesso, logo nossa equipe entrará em contato com você". Essa interação visa proporcionar uma experiência positiva ao candidato e confirmar que seus dados foram recebidos. Correto?
@lairareis, para garantir uma comunicação transparente e eficiente com todos os candidatos, nossa equipe de recrutamento se compromete a entrar em contato com cada pessoa que se inscrever no processo seletivo? Caso um candidato não seja considerado aderente ao perfil desejado para a vaga, nossa equipe de recrutamento ou o Head da área será responsável por enviar um e-mail gentil informando a decisão? ou seguimos outro fluxo?

**21**e**24-** Após o cliente optar por "sim", ele será automaticamente redirecionado para a página inicial ("home"). Com o objetivo de aprimorar a experiência do candidato, reconhecemos a importância de fornecer uma confirmação clara e imediata sobre sua inscrição na vaga. Para atender essa necessidade, estamos trabalhando na implementação de uma mensagem de confirmação que será exibida na tela logo após o candidato clicar em "sim". Essa mensagem informará que sua inscrição foi registrada com sucesso e nossa equipe de recrutamento entrará em contato em breve. Além disso, visando garantir a transparência e comunicação efetiva, devemos desenvolver um e-mail automático de confirmação que será enviado ao candidato logo após sua inscrição ser concluída. Esse e-mail conterá os detalhes da inscrição, o perfil da vaga e instruções sobre o próximo passo do processo seletivo.

**Comment by vinijardim-ux** [comment]
Protótipo do e-mail de retorno para o candidato.

Apresentação:
https://www.figma.com/proto/jSRZ3oteNw72k5a53sEwRq/SITE---Sou-Junior--Ago-2023?page-id=3167%3A15581&type=design&node-id=3528-40&viewport=-1238%2C475%2C0.65&t=7p52e1Ljo6AIgrG8-1&scaling=min-zoom&starting-point-node-id=3528%3A40&show-proto-sidebar=1&mode=design

Arquivo:
https://www.figma.com/file/jSRZ3oteNw72k5a53sEwRq/SITE---Sou-Junior--Ago-2023?type=design&node-id=3167%3A15581&mode=design&t=te5MVZWiDFrEr3rg-1

**Comment by sabrinamir** [comment]
@limaricardo @wandersonDeve esta US está parada. Poderiam validar?

**Comment by sabrinamir** [comment]
@brcaua e @wandersonDeve  poderiam validar a parte de frontend e backend para finalizarmos esta US?

**Comment by sabrinamir** [comment]
@brcaua e @joaop poderiam validar?

**Comment by sabrinamir** [comment]
@brcaua e @joaop poderiam validar?
