### ISSUE TITLE
[Sou apoiador] Trocar mensagem de obrigatoriedade dos campos

### ISSUE THREAD

**Issue by RntSaturnino** [SouJunior/products#318]
- **LINK DA US DE REFERÊNCIA: https://github.com/SouJunior/products/issues/50

- **DESCRIÇÃO DO BUG:** Alterar as descrições de obrigatoriedade   

- **EVIDÊNCIA:** 

![Image](https://user-images.githubusercontent.com/115566254/250168550-1529be7b-cc62-4c18-9e2f-fcc2f963a5fe.png)

 **SOLUÇÃO**Alterar os campos de obrigatoriedade de 

“Nome” para "O campo nome é obrigatório." 
“Telefone” para  "O campo telefone com DDD é obrigatório." 
“email” para "O campo E-mail é obrigatório."

**Comment by igords-goncalves** [comment]
Alterações realizadas 

![Image](https://github.com/SouJunior/products/assets/79734585/79f4ad8a-9a2b-4b68-87fe-0b85200d641f)
