### ISSUE TITLE
[SPIKE] Integração com Calendly

### ISSUE THREAD

**Issue by talitabitencourt** [SouJunior/products#339]
Estudo para entendimento da integração da nossa plataforma com a calendly

- Avaliar impedimentos e complexidades
- Retirada de duvidas com os Heads (Back e Front)

Link: 
https://calendly.com/pt
https://help.calendly.com/hc/en-us/categories/203261727-Integrations-Automations

**Comment by hudson-viana** [comment]
Card movido para finalizado pois:

- mentor cadastra o link calendly de acordo com essa US https://github.com/SouJunior/products/issues/426

- mentor edita o link calendly de acordo com esse card https://github.com/SouJunior/mentores-frontend/issues/216

**Comment by andremomesso** [comment]
Estou encerrando esta demanda, pois a mesma já está em Produção.
