### ISSUE TITLE
Adição de campos no formulário cadastro do Juninho

### ISSUE THREAD

**Issue by TayTeixeira** [SouJunior/products#413]
LINK DA US DE REFERÊNCIA: https://github.com/SouJunior/site-soujunior/issues/122

DESCRIÇÃO DA ATUALIZAÇÃO: A equipe de backoffice do RH realizou um mapeamento e identificou a necessidade de implementar duas novas funcionalidades no formulário de cadastro do 'Juninho' em nosso site. As adições propostas visam otimizar o processo de coleta de informações relacionadas à disponibilidade dos usuários. Os campos a serem introduzidos são: Campo de Pergunta sobre Disponibilidade Semanal e Campo de Pergunta sobre Horários Disponíveis no Dia. Também foi feito alterações nas perguntas e na opção das áreas de interesse

EVIDÊNCIA:

Imagem antes de aplicar a atualização:

![Image](https://github.com/SouJunior/site-soujunior/assets/31568030/29133b6c-a5b6-42a2-8c92-c0d0ff908ff3)

Alta fidelidade com atualização:

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?page-id=3994%3A318&type=design&node-id=4042-161&viewport=428%2C577%2C0.14&t=7FnUzF1nkYCnf5LO-1&scaling=min-zoom&mode=design

SOLUÇÃO: 
1- No preenchimento do formulário do Juninho, implementaremos dois novos campos de preenchimento para melhorar a gestão de tempo e disponibilidade dos usuários. Serão adicionados dois campos distintos ao formulário:

Campo de Disponibilidade Semanal: Este campo permitirá que o usuário selecione os dias da semana nos quais está disponível. A interface será projetada para facilitar a seleção múltipla de dias, com opções claras para cada dia da semana.
Deverá ser colocado a seguinte pergunta:
"Quais são os dias da semana em que você tem disponibilidade para atuar na Sou Junior?"

Campo de Horários Disponíveis no Dia: Complementar ao campo de disponibilidade semanal, este campo possibilitará que o usuário especifique os horários em que está disponível em cada um dos dias selecionados. A interface deste campo oferecerá uma seleção de horários em intervalos pré-definidos, permitindo ao usuário uma escolha detalhada e flexível de suas horas disponíveis.
Deverá ser colocado a seguinte pergunta:
"Qual é o período do dia em que você geralmente tem disponibilidade para atuar na Sou Junior?"

Esses campos serão posicionadas abaixo do campo existente 'Quanto tempo você tem disponível para atuar na Sou Junior? *'.

2- Na pergunta "Qual das opções abaixo, seria sua área de atuação/interesse?" deixar apenas a nomenclatura "área de interesse" na pergunta. Sendo assim a pergunta ficaria "Qual das opções abaixo seria sua área de interesse?"

3-Alteração do texto "Pode me contar um pouco sobre o motivo que o(a) levou a escolher essa área de atuação?" para "Conte-me um pouco sobre o motivo que o(a) levou a escolher essa área de atuação."

4- Nas áreas de interesse, retirar a opção "mobile", pois foi desativada.

**Comment by TayTeixeira** [comment]
@Vanessapcs você pode validar por favor?
Se for necessário melhorar escrita, modificar algo, só avisar!

**Comment by Vanessapcs** [comment]
@TayTeixeira precisamos conversar, pois pelo que você escreveu (em relação ao horário disponível) e o que está sendo apresentado no figma, não está conectando. No texto você fala que a proposta é "este campo possibilitará que o usuário especifique os horários em que está disponível em cada um dos dias selecionados", mas no figma temos apens UMA lista (independente de quantos dias da semana ele escolher) com as opções "manhã", "tarde" e "noite" (que ao meu ver também deve ser de múltipla seleção).

Acho que poderíamos deixar a opção de área de interesse como "múltipla seleção". E também acho que poderíamos usar apenas a nomenclatura "área de interesse" para tudo e removermos a descrição "área de atuação", pois deixa muito grande.

**Comment by sabrinamir** [comment]
@brcaua poderia validar?

**Comment by sabrinamir** [comment]
@brcaua poderia validar?
