### ISSUE TITLE
Correção de texto - Seção 'Confirme seu e-mail'

### ISSUE THREAD

**Issue by TayTeixeira** [SouJunior/products#415]
LINK DA US DE REFERÊNCIA: [Sou Apoiador - Página para Cadastro#50](https://github.com/SouJunior/products/issues/50)

DESCRIÇÃO DA ALTERAÇÃO: Na página do formulário "Sou Apoiador", ao acessar a seção "Confirme seu e-mail" e inserir o endereço de e-mail, observa-se que a mensagem de aviso está escrita incorretamente como "Confirmar email".

EVIDÊNCIA:

![Image](https://github.com/SouJunior/site-soujunior/assets/31568030/5c71ce67-2734-4171-aecf-b731f0432872)

![Image](https://github.com/SouJunior/site-soujunior/assets/31568030/e804e209-e7ab-44c2-a097-18e7d0a6bd50)

SOLUÇÃO: Modificar a mensagem de aviso de "Confirmar email" para "Confirmar e-mail" na seção "Confirme seu e-mail" dentro da página do formulário "Sou Apoiador".

**Comment by sabrinamir** [comment]
@brcaua poderia validar?

**Comment by sabrinamir** [comment]
@brcaua poderia validar?
