### ISSUE TITLE
Sou Apoiador - Página para Cadastro

### ISSUE THREAD

**Issue by Vanessapcs** [SouJunior/products#50]
**Definição:**

**Como** usuário,
**Gostaria** de demonstrar interesse em ser apoiador da Sou Junior, 
**Tendo** acesso a mais informações sobre como apoiar nos projetos.

**Descrição:**

Para que o usuário interessado em apoiar formalize o seu interesse será necessário realizar uma inscrição pelo site, na aba "Sou Apoiador".

**Protótipo:**

![Image](https://user-images.githubusercontent.com/115566254/231168989-28e0bd16-33ed-4128-956a-8dc2b8dbf0a2.png)

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/SITE---Sou-Junior?page-id=441%3A2293&node-id=581-6474&viewport=-442%2C870%2C0.22&scaling=scale-down-width&starting-point-node-id=448%3A1808

**Critérios de aceite** 

**1-** O Apoiador entrará no site da **SouJunior;**

**2-** O usuário poderá clicar em "**Participar**" e ser direcionado para a seção "**Quem pode participar**";

**3-** O usuário poderá rolar a página do site e ir até a seção "**Quem pode participar**" e Clicar na opção "**Sou Apoiador**";

**4-** Ao clicar na seção **"Sou Apoiador"**, o usuário terá acesso à descrição da seção;

**5-** Ao clicar no botão "**Quero Participar**" o usuário será redirecionado para outra página, para fazer sua inscrição;

**6-** Na página de inscrição o usuário deverá preencher os dados obrigatórios manualmente;

**7-** O usuário deverá selecionar obrigatoriamente a opção "**Pessoa física**" ou "**Pessoa jurídica**"; 

**8-** O usuário deverá informar seu nome ou o nome da instituição apoiadora;

- O campo “Nome completo” deverá ter capacidade para 100 caracteres.

**9-** O usuário poder preencher como prefere ser chamado, podendo ser uma apelido, ou nome social, não sendo obrigatório;

- O campo “Apelido” deverá ter capacidade para 100 caracteres.

**10-** O campo "**telefone/Whatsapp**" deve ser preenchido manualmente e obrigatoriamente;

**11-** O campo "**Confirme seu telefone**" deve ser preenchido manualmente e obrigatoriamente;

**12-** Caso o campo "**Telefone/Whatsapp**" possua um (DDD) inválido ou uma sequência ilógica, como "**0000-1111**" deve ser apresentada a seguinte mensagem ao usuário: “**telefone inválido**  abaixo do campo.

**13-** Caso os campos de telefone e confirmação de telefone estejam divergentes, deverá ser apresentada a mensagem "**telefone divergente**." abaixo do campo.

**14-** O campo "**e-mail**" deve ser preenchido manualmente e obrigatoriamente;

**15-** O campo **"confirme seu e-mail"** deve ser preenchido manualmente e obrigatoriamente; 

**16-** Para ser considerado um e-mail válido o mesmo dever conter o símbolo de @ + o domínio do e-mail + .com/.net/.br 

- Caso o e-mail não siga os critérios de validação, então o sistema deverá apresentar uma mensagem abaixo do campo com a descrição: **E-mail inválido.**

**17-** Caso os campos de e-mail e confirmação estejam divergentes, deverá ser apresentada a mensagem "**e-mail divergente**  abaixo do campo.

**18-** O campo "**Como você deseja apoiar a SouJunior**" deverá ser de preenchimento manualmente.

**19-** Caso os campos obrigatórios não forem preenchidos, ao clicar em "**Enviar**"  aparecerá uma mensagem em vermelho no campo não preenchido "**o campo não foi preenchido**";

**20-** Após o último campo, existirão um botões: "**Enviar**" 

**21-** O usuário deverá ter acesso ao botão "**Enviar **" para enviar os dados preenchidos;

**22-** Quando o usuário clicar em "Enviar", aparecerá uma pop-up com a mensagem "**Dados enviados com sucesso, logo nossa equipe entrará em contato com você**"

**23-** Os dados do usuário deverão ser direcionados para o e-mail do  "**Brandão**"; [wouerner@soujunior.tech]

**24-** O usuário será redirecionado para a "home" após clicar em "**Enviar**";

**25-** Se o usuário clicar em **voltar** no canto superior a esquerda caso desista de preencher os dados;

**26-** Após clicar em "**Voltar**" aparecerá um pop-up com um botão escrito "**Você deseja mesmo cancelar a inscrição?" com a opção "sim" e "não"**;

**27-** Caso o cliente opte por "**sim**" ele será redirecionado para a "**home**";

**28-** Caso o cliente opte por "**não**" os dados continuarão preenchidos e ele deverá clicar em "**Enviar**" para enviar a inscrição.

**29**- Os demais formulários dos campos "**SouJunior**", "**Sou Mentor**" deverão ter a opção "**Pessoa apoiadora ou parceira**" retirada, visto que para todos os campos, o mesmo forms é utilizado.

**Comment by Vanessapcs** [comment]
@midigalvao 

Alguns pontos importantes:
- Você não converteu a US para "issue". Favor ler o processo de andamento das US e seguir o passo a passo para facilitar a execução do fluxo.
- Você não numerou os critérios de aceite. Precisamos que estejam para que torne mais prático a identificação dos critérios na validação aqui nos comentários. Já que mencionamos apenas o numero do critério e colocamos nossas considerações. Sem a numeração, ficará complicado você saber que critério estou corrigindo. Isso também está mencionado no texto do fluxo, favor ler.
- É só clicar no ícone (ver imagem a seguir) e ler o procedimento:

![Image](https://user-images.githubusercontent.com/91374502/216820706-1dc1fdf6-8895-4e35-b526-389bdcafc1bd.png)

Outros pontos sobre a US:

- O apoiador não fará login. Não teremos login no Site. A US é sobre a mudança do formulário de apoiador que existe hoje no site para algo mais robusto e interessante. Portanto:
> O desejo do Usuario será apenas "participar como apoiador da iniciativa".
> Para isso, ele não precisará de login, já que é so entrar no site, ir na seção "Quem pode participar?" e selecionar a opção "Quero Participar" da área "Sou apoiador", de acordo com a imagem abaixo:

![Image](https://user-images.githubusercontent.com/91374502/216821016-a3504d20-81c9-4482-8deb-44d89aabb102.png)

> Depois de avisar que o Usuário será direcionado para o formulário de cadastro de interesse, a mudança acontece. Hoje, ele é direcionado para um form genérico e a US definirá uma tela para esse cadastro de interesse acontecer. Portanto, você precisará pensar nos campos importantes para esse novo cadastro, criar um protótipo com os campos e componentes, escrever os critérios de aceite dessa tela, perguntar na SouJunior para que email é direcionado o formulário hoje e colocar essa informação na US também.
> Então você tem muito trabalho pela frente. Qualquer dúvida me chama. Assim que tiver ajustada, me marca aqui para que eu possa validar.

**Comment by Vanessapcs** [comment]
@midigalvao você finalizou os ajustes? Posso revalidar?

**Comment by midigalvao** [comment]
@Vanessapcs tudo bem?
Finalizei o protótipo e critérios de aceite

**Comment by andyarauj0** [comment]
@midigalvao 

- Na definição, ficou estranho "como apoiador, eu gostaria de efetuar uma inscrição para me tornar apoiador..." Se ele esta interessado em ser apoiador, ele ainda não apoia a causa; O mesmo vale para a descrição. Pode ser assim : "Para que o interessado em apoiar a iniciativa formalize o seu interesse, será necessário realizar uma inscrição pelo site, na aba "Sou Apoiador"."

- Na descrição abaixo da imagem, seria interesse falar que o interessado receberá contato do nosso time e não especificar tanto assim de qual time ele vai receber esse contato;

- Sobre a imagem, você pode sinalizá-la como uma observação no protótipo. Por que você pensou em ser o Hero da página inicial? acho que podemos explorar alguma outra imagem, principalmente por se tratar de uma nova página que vai ser aberta e para não confundir o usuário com a página inicial. O que acha? 

**Sobre os critérios de aceite, segue as minhas observações:**

 2 - Ao clicar em participar o usuário não será direcionado para a página de sou apoiador, mas sim para a sessão de "quem pode participar";

obs.:  Faltou um critério de aceite entre o 6 e 7 falando sobre a escolha da pessoa física e a jurídica; 

7 - Não entendi esse processo. Ele vai digitar o e-mail e na mesma hora vai receber um token? Acha que faz sentido para a experiência do usuário? Podemos pensar em outras formas de validar o e-mail, como pedir para confirmar o e-mail, não seguir o processo caso a informação não esteja completa ex.: @gmail.com e etc;

8 - A mesma provocação de cima se mantém aqui;

11- Vamos colocar esse campo do por que e como obrigatórios? acho que perdemos muito caso a pessoa não expresse seu interesse de antemão;

15 - eu deixaria esse critério de aceite por último, para amarrar a finalização do processo; 

17 - Eu acho que esse critério de aceite precisa vir logo após o o 14, para dar sequenciamento lógico ao processo. Na sequencia que está há um rompimento do flow;

16 - Acho que seria melhor um botão com outra informação. Como o botão de enviar os dados é "continuar", aqui poderia ser outra coisa, tipo "voltar para o menu". Vale pensar num descritivo mais sucinto kkk.

**Comment by midigalvao** [comment]
@andyarauj0 tudo bem?
Realizei as alterações e incluí alguns critérios de aceite.
Também realizei a alteração no protótipo, pode dar uma olhadinha?

**Comment by andyarauj0** [comment]
@Samueldiasp quando vc for conversar com o time de UX, leva essa US para eles ja pensarem no protótipo de alta fidelidade tbm. Belê?

**Comment by RntSaturnino** [comment]
@priscilassouza fiz os ajustes que comentamos ontem

**Comment by EduBeserra** [comment]
Boa tarde, segue a versão inicial do protótipo da pagina de cadastro para apoiadores

https://www.figma.com/proto/XoZ6GKJ854Zxb0OvqNTlEh/FAQ-Sou-Junior?page-id=441%3A2293&node-id=448%3A1808&viewport=-141%2C1523%2C0.37&scaling=scale-down-width&starting-point-node-id=451%3A2683

**Comment by EduBeserra** [comment]
Tomei a liberdade de alterar o desenho no topo, acredito que desenhos diferentes em telas diferentes criam um ambiente acolhedor e envolvente para o usuario, como uma historia sendo contada. Claro é apenas uma sugestão, posso facilmente colocar o desenho usado na home.

**Comment by EduBeserra** [comment]
Fico no aguardo do feedback de vocês.

**Comment by RntSaturnino** [comment]
Oi Edu, adoramos pode continuar, parabéns pelo trabalho.

**Comment by sabrinamir** [comment]
@limaricardo @wandersonDeve esta US está parada. Poderiam validar?

**Comment by sabrinamir** [comment]
@brcaua e @wandersonDeve  poderiam validar a parte de frontend e backend para finalizarmos esta US?

**Comment by brcaua** [comment]
Validado.

**Comment by sabrinamir** [comment]
@JoaoPauloAmendolaDev  poderia validar?

**Comment by JoaoPauloAmendolaDev** [comment]
validado
