### ISSUE TITLE
Levantamento e atualização de Squads.

### ISSUE THREAD

**Issue by AyumiHanada** [SouJunior/products#537]
**O  QUÊ ?**
Atualizar as Squads  com os mentores e júniores envolvidos na SouJunior.

**POR  QUÊ ?**
Precisamos ter claro quem iremos acionar quando ocorrer uma demanda. Para solucionar as dores a atualização das Squads facilita a comunicação entre os júniores.

**COMO ?**
Atualizar a lista dos Squads junto a Header (Vanessa) responsável pela seleção e exclusão de voluntário da SouJunior, quando houver demandas.

**LINK**
Tabela geral: https://docs.google.com/spreadsheets/d/1zuh5ZQbmZHKridCpTy0WZwpDJ2nDFVCG5S3sVkjBCfI/edit#gid=1049322900 

Tabela atualizada:
https://docs.google.com/spreadsheets/d/1w0AqoP7wZcT6Gq41YXPGvLI4S3i8ZW9R/edit?usp=drive_link&ouid=105808865795524722819&rtpof=true&sd=true 

**STAKEHOLDER**
Vanessa e Juniores. 

**TAREFAS**
 Consultar a Head quando houver demanda.

![Image](https://github.com/user-attachments/assets/550f4b1f-053e-4820-8783-ccd0fa2b69db)

**Comment by olavoanselmo** [comment]
Preparação do CARD sobre levantamento e atualização das Squads.
