### ISSUE TITLE
Reestruturação do Formulário para Apoiadores - Site

### ISSUE THREAD

**Issue by TayTeixeira** [SouJunior/products#642]
---

Formulário para Apoiadores - Site
about: User Story do Produto "Site".
title: "[Reestruturação do Formulário para Apoiadores - Site]"
labels: ''
assignees: ''

---
___________________________________________________________________________________________________________

**Definição**

Como apoiador, eu desejo contribuir para o projeto, seja como financiador, divulgador, palestrante, recrutador ou empresa, para promover o desenvolvimento de profissionais juniores em tecnologia.

___________________________________________________________________________________________________________

**Descrição**

Esta User Story aborda a necessidade de duas squads da SouJunior, a do Site e a do Backoffice RH, que estão colaborando para reestruturar o formulário para apoiadores. O objetivo é satisfazer tanto as necessidades dos apoiadores, que desejam mais informações sobre como contribuir, quanto as do RH da SouJunior, que precisa de dados para realizar um gerenciamento eficiente dos novos colaboradores. Como parte dessa iniciativa, também será desenvolvida uma página com a identidade visual da SouJunior.
___________________________________________________________________________________________________________

**Protótipos**
Wireframes ou fluxgramas que representem visualmente a User Story descrita.
___________________________________________________________________________________________________________

**Critérios de Aceite**

1- O usuário entrará no site da SouJunior.

2- O usuário irá clicar em "Faça parte" e será direcionado para a seção "Faça você também parte da nossa comunidade!".

3- Ao clicar na seção "Sou Apoiador", o usuário terá acesso à descrição da seção.

3- Ao clicar no botão "Quero Participar!", o usuário será redirecionado para outra página para fazer sua inscrição.

5- O formulário deve permitir que o usuário escolha entre Pessoa Física ou Pessoa Jurídica.
Campo obrigatório
 
6- O campo "Nome Completo" estará visível apenas se Pessoa Física for selecionada, e aceitará apenas nomes pessoais.

7-  campo "Instituição/Afiliada" estará visível apenas se Pessoa Jurídica for selecionada, e aceitará apenas caracteres válidos para nomes de instituições.

8- O campo "Telefone" será obrigatório e aceitará apenas números válidos para números de telefone.

9- O usuário deverá informar o e-mail e confirmar no próximo campo.
Para ser considerado um e-mail válido, ele deve conter o símbolo de @ + o domínio do e-mail + .com/.net/.br.
Campo obrigatório
Caso o e-mail não siga os critérios de validação, o sistema deverá apresentar uma mensagem abaixo do campo com a descrição: "E-mail inválido."

10- O campo "Como você gostaria de apoiar o SouJunior?" permitirá selecionar uma ou mais opções entre:
- [ ] Financiador da iniciativa
- [ ] Divulgador (YouTube, podcast, blog sobre tecnologia)
- [ ] Especialista disposto a palestrar
- [ ] Recrutador
- [ ] Empresa interessada em contratar
- [ ] Outras formas de apoio _____________

11- Se "Divulgador" for selecionado, o campo "Se você selecionou 'Divulgador', por favor, forneça o link para o seu canal/plataforma" será visível e aceitará URLs válidos.

12- Se "Especialista disposto a palestrar" for selecionado, o campo "Se você selecionou 'Especialista disposto a palestrar', por favor, descreva sua área de expertise" será visível e aceitará caracteres válidos para descrição de áreas de expertise.

13- Se "Recrutador" ou "Empresa interessada em contratar" forem selecionados, o campo "Se você selecionou 'Recrutador' ou 'Empresa interessada em contratar', por favor, descreva as oportunidades disponíveis" será visível e aceitará caracteres válidos para descrição de oportunidades.

14- O campo "Você possui alguma sugestão ou ideia específica para contribuir com a SouJunior?" aceitará caracteres válidos para descrição de sugestões ou ideias.

15- O campo "Qual é a sua motivação principal para se juntar a SouJunior?" aceitará caracteres válidos para descrição da motivação.

16- Após clicar em "Enviar", se algum campo obrigatório não estiver preenchido, exibir mensagem "O campo não foi preenchido."

17- Após preencher todos os campos obrigatórios e aceitar os termos, o botão "Enviar" será ativado.

18- Após clicar em "Enviar", exibir pop-up com mensagem "Inscrição concluída. Você receberá um e-mail de confirmação em breve."

19- Enviar e-mail de confirmação da inscrição para o usuário.

20- Direcionar os dados do usuário para uma planilha gerenciada pela Squad de Backoffice.

21- Após clicar em "Voltar" ou atualizar a página, mostrar pop-up com opção "Você deseja mesmo cancelar a inscrição?" (Sim / Não)
- Se optar por "Sim", redirecionar para a "home".
- Se optar por "Não", manter dados preenchidos e exigir novo clique em "Enviar" para enviar a inscrição.

22- Após clicar em "Enviar", o usuário será redirecionado para a "home".

___________________________________________________________________________________________________________

**Informações Adicionais**
Qualquer observação importante para melhorar o entendimento da User Story
___________________________________________________________________________________________________________

**DoR - Definition of Ready**
- [ ] O design/wireframe foi definido e aprovado.

- [ ] A tarefa foi priorizada de acordo com o backlog e com as necessidades.

- [ ]  Os critérios de aceite estão claramente definidos a serem executada pela equipe.

- [ ] As dependências do projeto foram identificadas e resolvidas e documentadas.

- [ ] A equipe entendeu e concordou com as definições de "pronto" para a tarefa.
___________________________________________________________________________________________________________

**DoD - Definition of Done**
- [ ] Todos os requisitos funcionais definidos foram implementados e testados.

- [ ] O site está em conformidade com as especificações.

- [ ] O site é responsivo e funciona em diferentes tamanhos de tela e dispositivos.

- [ ] O site é acessível para usuários com deficiência.

- [ ] O tempo de carregamento da página é aceitável.

- [ ] O código foi testado por meio de testes automatizados.

- [ ] Os testes de aceitação do usuário foram realizados com sucesso.

- [ ] O design do site está de acordo com as diretrizes definidas.

- [ ] O site é esteticamente atraente e fácil de usar.

- [ ] A documentação do código é completa e atualizada.

- [ ] A documentação do usuário está disponível e é fácil de usar.

- [ ] O site foi implantado com sucesso no ambiente de produção.

- [ ] As configurações do servidor foram realizadas conforme as especificações definidas pelo cliente.name: Reestruturação do

**Comment by TayTeixeira** [comment]
@IsabellaMaciel  Boa noite, tudo bem?
Poderia validar essa US, por favor?

**Comment by IsabellaMaciel** [comment]
@TayTeixeira Alinhado, incluir opção "Outra formas de apoio"

**Comment by IsabellaMaciel** [comment]
"14" corrigir o período assim como outros formulários

**Comment by sabrinamir** [comment]
Processo arquivado devido a alteração para que Backoffice crie o formulário de uma forma diferente.
