### ISSUE TITLE
Correção áreas de atuação - Formulário Juniores

### ISSUE THREAD

**Issue by TayTeixeira** [SouJunior/products#643]
LINK DA US DE REFERÊNCIA: https://github.com/orgs/SouJunior/projects/9?pane=issue&itemId=63627862

DESCRIÇÃO DA ALTERAÇÃO: As áreas de Tech Recruitment e Business não foram incluídas na seção de áreas de atuação no formulário de juniores. 

EVIDÊNCIA:

![Image](https://github.com/SouJunior/products/assets/31568030/b97e811d-a4d8-4144-87c9-1ba0d15b3cab)

SOLUÇÃO: Para resolver a ausência das áreas de Tech Recruitment e Business na seção de áreas de atuação no formulário de juniores, vamos atualizar o formulário adicionando essas categorias. Isso garantirá que todos os setores relevantes para a SouJunior estejam representados, proporcionando uma melhor experiência para os candidatos e facilitando o processo de seleção para o RH.

**Comment by TayTeixeira** [comment]
@IsabellaMaciel Boa noite, tudo bem?
Poderia validar esse card, por favor?

**Comment by IsabellaMaciel** [comment]
Alinhado e validado contigo agora mesmo! hehe

**Comment by sabrinamir** [comment]
Processo arquivado devido a alteração para que Backoffice crie o formulário de uma forma diferente.
