### ISSUE TITLE
Planejamento mensal | Julho

### ISSUE THREAD

**Issue by jusomidias** [SouJunior/products#654]

**Comment by TamisLima** [comment]
Oii gente!!

Deixando o planejamento mensal de julho e o cronograma da primeira semana de posts anexado aqui.

https://docs.google.com/document/d/16SdLVq9vfCjFkDTXwuG5f7DrXLb56YHOSKvjCdQHL7k/edit?usp=drive_link (Esse é o planejamento mensal)

https://docs.google.com/document/d/1zf0vkjD1sQMTRTmt_i5xPPY0c_lUNQegcEW-e1Fkb-c/edit?usp=drive_link (Cronograma mensal)

**Comment by belit-lua** [comment]
Arte 1



![Sem título](https://github.com/user-attachments/assets/9593d132-7dc3-4366-bf2d-80a30f01d35d)
![Sem título (1)](https://github.com/user-attachments/assets/36fe2cde-3838-4de6-b41e-819fd42081ac)
![Sem título (2)](https://github.com/user-attachments/assets/76eecffc-7f33-4510-b616-1532f74602cf)
![Sem título (3)](https://github.com/user-attachments/assets/8ec63a7f-99d5-4148-90f7-6f793e1344f5)

**Comment by belit-lua** [comment]
Arte 2
![Sem título (4)](https://github.com/user-attachments/assets/0a47a889-aec0-4b58-95b1-9b453a2acbbf)
![Sem título (5)](https://github.com/user-attachments/assets/275d913b-885e-4104-920f-419973af7f28)
![Sem título (8)](https://github.com/user-attachments/assets/709ccca3-7bae-4f0e-9c83-7825dc571b9a)
![Sem título (9)](https://github.com/user-attachments/assets/d0bc5414-904f-4d23-ae36-d6143b282110)
![Sem título (11)](https://github.com/user-attachments/assets/a9c353dd-1977-43a4-80d9-b25f863d3ab5)
![Sem título (12)](https://github.com/user-attachments/assets/adffa553-b26d-43ff-ab50-8bed4aff06e3)

**Comment by jusomidias** [comment]
Bom dia, meninas!

@belit-lua **primeira arte** que enviou está toda ok! Só irei repassar para a Vanêssa e o Brandão confirmarem e aviso para postarem. Você consegue enviá-las em link?

**Na segunda arte**, só tenho dois pontos para melhoria: 

- Tirar a marca d'água da logo da segunda arte em diante; 
- Na terceira arte, a linha 3 de texto está muito perto da margem então precisa ser alterado.

Assim que fizer essas mudanças me avisa, tá bom? @belit-lua 

Ótimo trabalho meninas!!! 😍

**Comment by belit-lua** [comment]
Alterações solicitadas:
![j1](https://github.com/user-attachments/assets/e4dcd978-7435-4b29-8028-594f8f2dd4e4)
![j2](https://github.com/user-attachments/assets/495a5aff-72d4-4749-8df4-df15aa046970)
![j3](https://github.com/user-attachments/assets/72067cf5-871d-4535-8ceb-00f2295a9a7d)
![j4](https://github.com/user-attachments/assets/83b746e0-b0a4-4c95-a918-43f0d635def3)
![j5](https://github.com/user-attachments/assets/9f58beee-b0bc-450e-bdb5-e6bc6d4c8777)
![j6](https://github.com/user-attachments/assets/cad15009-c5a1-4ae2-a557-c48702e43f98)

**Comment by jusomidias** [comment]
Ficou ótimo! 😍

@belit-lua me manda o link desses designs para que eu envie para a Vanêssa e o Brandão, por favor. No formato que enviou não estou conseguindo baixar.

**Comment by jusomidias** [comment]
Olá, meninas @belit-lua e @TamisLima 

@belit-lua o Brandão pediu uma alteração nessa **_primeira arte_** onde falamos sobre o portal de vagas. Será inserir o endereço do site dentro da imagem também.

O que te indico a fazer: 

- Diminuir os elementos em cada arte e colocar abaixo dos elementos: vagas.soujunior.tech/

**Sobre o segundo post, _ele foi aprovado_**, então sem necessidade de mudanças. Ótimo trabalho, meninas!

Assim que fizer as alterações, me avise para que eu veja se está tudo certo e podermos liberar o post!

**Comment by belit-lua** [comment]
Alteração:
![sou junior portal](https://github.com/user-attachments/assets/158a879e-8aa1-4677-ad36-b1059be4907a)

**Comment by jusomidias** [comment]
@belit-lua **abaixo dos elementos**, não da caixa de texto. E em todas as páginas da arte. 

Você pode diminuir os elementos em cada arte e colocar abaixo dos elementos: vagas.soujunior.tech/ _(pode aplicar transparência no nome do site e deixá-lo em um tamanho pequeno)._

**Comment by belit-lua** [comment]
Vídeo sextou 
https://new.express.adobe.com/id/urn:aaid:sc:US:89a0fba8-b0c5-5b81-a50b-8b2fcdb62fd9?invite=true&promoid=Z2G1FQKR&mv=other

**Comment by jusomidias** [comment]
Olá!

@belit-lua preciso que faça as alterações solicitadas para o design sobre o Portal de Vagas para postarmos! 

Como havia dito: **o link é _abaixo dos elementos,_ não da caixa de texto. E em todas as páginas da arte.** 

O que você pode fazer é diminuir os elementos em cada arte e colocar abaixo dos elementos, o link: vagas.soujunior.tech/ _(pode aplicar um pouco de transparência no nome do site e deixá-lo em um tamanho pequeno)._ Se continuar com dúvida, pode me chamar.

Agora outra observação... Sobre esse design do sextou, não é o ideal que mande todas as criações em design nesse card aqui. Crie um card identificando a atividade e acrescente a arte, por favor.
