### ISSUE TITLE
Alteração - Formulário Juniores

### ISSUE THREAD

**Issue by sabrinamir** [SouJunior/products#687]
LINK DA US DE REFERÊNCIA: https://github.com/orgs/SouJunior/projects/9?pane=issue&itemId=63627862

DESCRIÇÃO DA ALTERAÇÃO: Incluir subáreas de Dados, Social Media e Business no formulário de juniores.

SOLUÇÃO: Para resolver a ausência da área de Social Media, na seção de áreas de atuação no formulário de juniores, vamos atualizar o formulário adicionando essa categoria. Para as subáreas, também serão adicionadas equipes específicas. Isso garantirá que todos os atuais setores da SouJunior estejam representados, proporcionando melhor experiência para os candidatos e facilitando o processo de seleção para o RH.

*Dados
( ) Analytics
( ) BI
( ) Engenharia de Dados

*Social Media
( ) Criação de conteúdo - Redação
( ) Criação de peças - Design

*Business
( ) Análise de negócios
( ) Análise de processos
( ) Outro: ___________

![Image](https://github.com/user-attachments/assets/81cf49a7-ec38-4e25-87a3-5e1c6c611027)

**Comment by sabrinamir** [comment]
@IsabellaMaciel  pode validar?

**Comment by IsabellaMaciel** [comment]
Oi @sabrinamir, pequenas sugestões de melhorias para discutirmos:

1 - "DESCRIÇÃO DA ALTERAÇÃO" é diferente de "Motivo da alteração".

Desse modo, "DESCRIÇÃO DA ALTERAÇÃO" Poderia ser "Incluir subáreas de Dados, Social Media e Business no formulário de juniores." OU substituir "Descrição" por "motivador".

2 - Em SOLUÇÃO:

- Incluir virgula após "Para resolver a ausência da área de Social Media";
- "para a SouJunior" >> "da SouJunior"; e
- "uma melhor experiência" >> "melhor experiência"

Concorda?

**Comment by IsabellaMaciel** [comment]
teste

**Comment by sabrinamir** [comment]
Prontinho @IsabellaMaciel  todos os pontos alterados, e concordo com todos <3

**Comment by GabrielOliveira9400** [comment]
Alteraçoes feitas e ja se encontram no site

**Comment by sabrinamir** [comment]
Processo arquivado devido a alteração para que Backoffice crie o formulário de uma forma diferente.
