### ISSUE TITLE
[Melhoria] - Formulário Juniores

### ISSUE THREAD

**Issue by TayTeixeira** [SouJunior/products#697]
Link da US de Referência: https://github.com/orgs/SouJunior/projects/9?pane=issue&itemId=63627862
Link do documento para referência de correção: https://docs.google.com/document/d/1wHlTnULJ6ckETRfLTQygPzoFaDQVrZ4BgsgBfJbsYbw/edit

### **Descrição da Alteração:** Temos 2 atualizações para serem feitas no formulário de juniores:

_1- Alterar pergunta do campo de horas obrigatórias de dedicação ao voluntariado no formulário de juniores_ 

**Antes** 
~~"Quanto tempo você poderia dedicar por semana ao voluntariado?"~~
( ) 5 horas
( ) 5 a 10 horas
( ) 10 a 15 horas
( ) Mais de 15 horas

**Depois** 
"**Quanto tempo você poderia dedicar por semana ao voluntariado?**"
( ) 5 horas
( ) 5 a 10 horas
( ) 10 a 15 horas
( ) Mais de 15 horas

-------------------------------------------------------------------------------------------------------------------------------------

_2- Deve ser removido o campo de escolha "Dentro de 30 dias"_ 

**Antes**
 Qual a sua disponibilidade para início?
( ) Imediato
~~( ) Dentro de 30 dias~~
( ) Outro: ___________

**Depois**
Qual a sua disponibilidade para início?
( ) Imediato
( ) Outro: ___________

-------------------------------------------------------------------------------------------------------------------------------------
_3- Deve ser alterado a escrita do "OPS" para "Ops"_ 
De: ~~"( ) Product OPS"~~
Para: "( ) Product Ops"

**Comment by TayTeixeira** [comment]
@IsabellaMaciel 
Valida por favor!

**Comment by IsabellaMaciel** [comment]
Oi, @TayTeixeira pequenas sugestões para discutirmos:

1 - Considerando que o respondente responderá com base em sua disponibilidade presente, sugiro a seguinte alteração: "Quanto tempo **você poderia** dedicar por semana ao voluntariado?" >> Quanto tempo **você pode** dedicar por semana ao voluntariado?"

2 - Tentar manter padrão de formatação, exemplo: "2-Deve" >> "2- Deve" 

O que acha?

**Comment by sabrinamir** [comment]
Processo arquivado devido a alteração para que Backoffice crie o formulário de uma forma diferente.
