### ISSUE TITLE
[Melhorias] - Formulário de Mentor

### ISSUE THREAD

**Issue by sabrinamir** [SouJunior/products#698]
LINK DA US DE REFERÊNCIA: https://github.com/orgs/SouJunior/projects/9?pane=issue&itemId=63627862

DESCRIÇÃO DA ALTERAÇÃO: Alteração de textos e exclusão de uma opção que está disponível.

SOLUÇÃO: Precisamos alterar 4 campos do formulário do mentor, conforme informações abaixo:
_____________________________________________________________________________
**Exclusão**:
1-Na questão "Qual a sua disponibilidade para início?" existem 3 opções. A opção "**Em até 1 mês**" deverá ser excluída.

De:
( ) Imediato
( ) Em até 1 mês
( ) Outro: ___________

Para:
( ) Imediato
( ) Outro: ___________
_____________________________________________________________________________
**Alteração:**
2- No campo onde preenchemos as horas semanais que temos disponível, alterar o enunciado da pergunta.

_De_:  "Considerando a participação mínima de 5 horas semanais para o projeto. Quanto tempo você poderia dedicar por semana ao voluntariado?"

_Para_: "Quanto tempo por semana você poderia se dedicar ao voluntariado?"
_____________________________________________________________________________
**Alteração:**
3- Quando selecionamos a área de produto e habilita a subárea para seleção, onse deverá ser alterado a escrita de "OPS" para "Ops".

_De_: "( ) Product OPS"

_Para_:  "( ) Product Ops"
_____________________________________________________________________________
**Alteração:**
4-No campo "Há quanto tempo você atua no mercado de trabalho?" alterar as formas de separação de tempo.
_De_: 
( ) 6 meses a 1 ano
( ) 1 a 3 anos
( ) 3 a 5 anos
( ) Mais de 5 anos

_Para_:
( ) 6 a 11 meses
( ) 1 a 3 anos
( ) 4 a 6 anos
( ) Acima de 6 anos

**Comment by IsabellaMaciel** [comment]
Oi, @sabrinamir , seguem alguns pontos para conversarmos:

1 - "Precisamos que seja alterado algun**s**" ou concordamos com o número ""Precisamos que sejam alterados algun**s**" ou substituímos de uma forma mais "amigável" para facilitar a leitura "Precisamos alterar algun**s**".

2 - "conforma" >> "conforme"

3 - "opções. a opção" >> "opções. A opção", aproveitando, deixaria em negrito a opção a ser excluída, exemplo: "(...) 3 opções. A opção "**Em até 1 mês**" deverá ser excluída."

4 - Considerando que o respondente responderá com base em sua disponibilidade presente, sugiro a seguinte alteração: "Quanto tempo por semana **você poderia** se dedicar ao voluntariado?" >> "você pode".

5 - **Dúvida:** O seguinte trecho ficou repetido?

De: "( ) Product OPS"
Para: "( ) Product Ops"

De: "( ) Product OPS"
Para: "( ) Product Ops"

6 - Como foi realizada a alteração 

De:
( ) 6 meses a 1 ano
( ) 1 a 3 anos
( ) 3 a 5 anos
( ) Mais de 5 anos
Para:
( ) 6 meses a 1 ano
( ) 1 a 3 anos
( ) 4 a 6 anos
( ) Acima de 6 anos

Considera válido deixarmos da seguinte forma?

Para:
( ) 6 a 11 meses
( ) 1 a 3 anos
( ) 4 a 6 anos
( ) Acima de 6 anos

7 - Por fim, tentaria deixar mais claro quantas são as alterações ou quando uma começa e termina. Podendo ser uma divisão por traços, numeração etc.

O que acha desses pontos? Concorda, discorda ou sugere algo?

**Comment by sabrinamir** [comment]
Prontinho @IsabellaMaciel, pontos alterados <3

**Comment by sabrinamir** [comment]
Processo arquivado devido a alteração para que Backoffice crie o formulário de uma forma diferente.
