### ISSUE TITLE
Inclusão de Rede Social - Tiktok

### ISSUE THREAD

**Issue by sabrinamir** [SouJunior/products#707]
LINK DA US DE REFERÊNCIA: https://github.com/SouJunior/site-soujunior/issues/117

DESCRIÇÃO DA ALTERAÇÃO: No rodapé da página, ainda não temos o ícone de tiktok.

EVIDÊNCIA:

![Image](https://github.com/user-attachments/assets/4e373ab2-dae8-4037-81c1-56b085570575)

SOLUÇÃO: Deverá ser adicionado o ícone de tiktok com com o link para encaminhamento da página.
Link: https://www.tiktok.com/@soujuniortech

Logo:
https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/tiktok-white-icon.png

**Comment by sabrinamir** [comment]
pode validar @IsabellaMaciel ?

**Comment by IsabellaMaciel** [comment]
@sabrinamir Oii, US validada!

------

Obs. para conhecimento não obrigatório: Poderíamos verificar com os Devs se eles precisam de png ou se seria apenas para UX, pois geralmente usam fa icon, como: 

<i class="fa-brands fa-tiktok"></i>

ou o link: https://fontawesome.com/icons/tiktok?f=brands&s=solid

**Comment by CryslaineGomes** [comment]
Cenarios de testes e ecidencias:
[Cenarios e evidencias - Tiktok #707.pdf](https://github.com/user-attachments/files/17177131/Cenarios.e.evidencias.-.Tiktok.707.pdf)
