### ISSUE TITLE
Alteração de escrita de Lab

### ISSUE THREAD

**Issue by sabrinamir** [SouJunior/products#708]
LINK DA US DE REFERÊNCIA: https://github.com/SouJunior/site-soujunior/issues/117

DESCRIÇÃO DA ALTERAÇÃO: A escrita da iniciativa da Sou Junior Labs está escrita de forma errada no site.

EVIDÊNCIA:

![Image](https://github.com/user-attachments/assets/112152c7-d8b3-4b46-9399-02448fb6b5e2)

________________________________________________
SOLUÇÃO: Deverá ser alterado o nome:
De: "SouJunior Lab" 
Para: "SouJunior Labs"

![Image](https://github.com/user-attachments/assets/40fc936e-1e48-43b9-8ee1-b4b8234cb401)

**Comment by IsabellaMaciel** [comment]
Incluir @sabrinamir 

![Image](https://github.com/user-attachments/assets/0cae0c06-f73e-4689-be22-720cb6f57db0)

**Comment by CryslaineGomes** [comment]
Cenário de teste e evidências:
[Labs #708.pdf](https://github.com/user-attachments/files/17081931/Labs.708.pdf)
