### ISSUE TITLE
[BACK] Alterar Rota de Companies para uma só

### ISSUE THREAD

**Issue by CamilaRoch** [SouJunior/products#738]
**Nome da US:**
[BACK] Alterar Rota de Companies para uma só

___________________________________________________________________________________________________________

**Descrição:**

Executa scrapper na URL correta a partir de enum

___________________________________________________________________________________________________________

**Critérios de Aceite**
/company/{name}/scrapp
ENUM "RELOCATEME" || "SIAEXPLAINS"

___________________________________________________________________________________________________________

**Comment by ariadnamorais** [comment]
@CamilaRoch Poderia esclarecer sobre os critérios de aceite dessa atividade?

Qual o resultado esperado ao chamar esse endpoint?
Deve gerar algum arquivo pra download contendo os dados, ou a resposta deve ser salva no banco, ou deve fazer as duas ações?

**Comment by isafurtado** [comment]
@Gustavonobregab fiz uns testes e dá sempre erro 400, tanto no Swagger, quanto no Insomnia, quanto no Postman. Coloquei as evidências no drive, dá uma olhada segue o link: https://docs.google.com/document/d/1zZnOOS6k1DGBAab4fRMS14wo1m9902MJW9gNejkHl_0/edit?usp=sharing

**Comment by Gustavonobregab** [comment]
> [@Gustavonobregab](https://github.com/Gustavonobregab) fiz uns testes e dá sempre erro 400, tanto no Swagger, quanto no Insomnia, quanto no Postman. Coloquei as evidências no drive, dá uma olhada segue o link: https://docs.google.com/document/d/1zZnOOS6k1DGBAab4fRMS14wo1m9902MJW9gNejkHl_0/edit?usp=sharing



De fato, o projeto precisa estar rodando localmente para que a requisição seja realizada com sucesso. Para resolver isso, poderíamos consultar diretamente o banco de dados, porém não tenho, e nem estou conseguindo o acesso @isafurtado .

Aguardando resposta das pessoas que tem o acesso pra te mandar


![Image](https://github.com/user-attachments/assets/48029a55-203c-44e9-a867-5a86b99a4f4a)
